spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:15432/user-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create # in prod set to update with db update scripts
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

server:
  port: 8081

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.ecommerce.user: DEBUG # Abilita i log DEBUG per il nostro codice applicativo

jwt:
  secret: ${JWT_SECRET:your-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm-change-in-production}